version: "3.7"

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "card-management"
      POSTGRES_USER: "cardlay"
      POSTGRES_PASSWORD: "cardlay"
    ports:
      - "9002:5432"
